pipelines:
  branches:
    master:
      - step:
          name: Security Scan
          script:
            - pipe: atlassian/git-secrets-scan:0.5.1
      - step:
          name: Building & Pushing docker image to AWS ECR Private repositories
          services:
            - docker
          script:
            - export TAG_NAME="latest.$BITBUCKET_BUILD_NUMBER"
            - echo $TAG_NAME
            - docker build -t $IMAGE:$TAG_NAME -f Dockerfile .
            - pipe: atlassian/aws-ecr-push-image:2.0.0
              variables:
                AWS_ACCESS_KEY_ID: $PUSH_AWS_ACCESS_KEY
                AWS_SECRET_ACCESS_KEY: $PUSH_AWS_SECRET
                AWS_DEFAULT_REGION: $AWS_REGION
                IMAGE_NAME: $IMAGE
                TAGS: "${TAG_NAME}"

definitions:
  services:
    docker:
      memory: 2048